version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "appsec"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "patch"
        - "minor"
